import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    ".vercel/**",
    // Vendored, pinned agent skills are third-party tooling, not application code.
    ".agents/skills/**",
    ".reference/**",
    "output/instagram/**",
    // Capacitor web bundles are generated by scripts/build-mobile.mjs and cap sync.
    "native-shell/**",
    "ios/App/App/public/**",
    "android/app/src/main/assets/public/**",
    // Default ignores of eslint-config-next:
    ".next/**",
    ".next-*/**",
    "out/**",
    "build/**",
    ".npm-cache/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
