'use client';
import{useState}from'react';import Link from'next/link';import{Button}from'@/components/ui/Button';import{useEntity,entityAction}from'./useEntity';
type Place={id:string;name:string;slug:string};type Checkin={id:string;arena_id:string;arena_name:string;arena_slug:string;is_demo:boolean;sport_name:string;started_at:string;state:'active'|'ended'|'expired'};
export function ActivityHistory(){const[offset,setOffset]=useState(0);const{data,error,loading,reload}=useEntity<Checkin[]>('/api/activity?offset='+offset);const recent=data?[...new Map(data.map(c=>[c.arena_id,c])).values()].slice(0,4):[];return <section className="arena-about"><h2>Seu histórico privado</h2><p>Encerrar ou expirar a presença mantém seu histórico. Essas datas são visíveis somente para você.</p>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">Carregando histórico…</p>}{offset===0&&!!recent.length&&<><h3>Arenas recentes</h3>{recent.map(c=><p key={c.arena_id}><Link href={`/arenas/${c.arena_slug}`}>{c.arena_name}</Link> · <Link href={`/checkin?arena=${c.arena_slug}`}>Novo check-in</Link></p>)}</>}<h3>Últimos check-ins</h3>{data?.slice(0,20).map(c=><article className="connected-panel" key={c.id}><Link href={`/arenas/${c.arena_slug}`}>{c.arena_name}{c.is_demo?' · demo':''}</Link><p>{c.sport_name} · {({active:'Ativo',ended:'Encerrado',expired:'Expirado'})[c.state]}</p><time dateTime={c.started_at}>{new Date(c.started_at).toLocaleString('pt-BR')}</time></article>)}{data?.length===0&&<p>Você ainda não tem check-ins registrados.</p>}<div className="read-pagination"><Button variant="quiet" onClick={reload}>Atualizar histórico</Button>{offset>0&&<Button variant="secondary" onClick={()=>setOffset(offset-20)}>Anterior</Button>}{data&&data.length>20&&<Button onClick={()=>setOffset(offset+20)}>Próxima</Button>}</div></section>}
export function ProfilePlaces({playerId}:{playerId:string}){const{data,error,reload}=useEntity<{own:boolean;share_activity_summary:boolean;arenas:Place[];communities:Place[]}>(`/api/activity?kind=places&player=${playerId}`);const[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <section className="arena-about"><h2>Picos e comunidades</h2>{error&&<p role="alert">{error}</p>}{data&&<><h3>Arenas acompanhadas</h3>{data.arenas.map(a=><p key={a.id}><Link href={`/arenas/${a.slug}`}>{a.name}</Link></p>)}{!data.arenas.length&&<p>Nenhuma arena acompanhada disponível.</p>}<h3>Comunidades</h3>{data.communities.map(c=><p key={c.id}><Link href={`/comunidades/${c.slug}`}>{c.name}</Link></p>)}{!data.communities.length&&<p>Nenhuma comunidade disponível para sua conta.</p>}{data.own&&<label className="checkbox-row"><input type="checkbox" checked={data.share_activity_summary} disabled={busy} onChange={async e=>{setBusy(true);try{await entityAction('/api/activity',{share:e.target.checked});reload();setMessage('Privacidade atualizada.')}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}}}/>Compartilhar total de check-ins e até cinco arenas visitadas, sem datas ou horários.</label>}<p role="status">{message}</p><ActivitySummary key={String(data.share_activity_summary)} playerId={playerId}/></>}</section>}
function ActivitySummary({playerId}:{playerId:string}){const{data}=useEntity<{total:number;arenas:Place[]}>(`/api/activity?kind=summary&player=${playerId}`);return data?<div><h3>Resumo de atividade</h3><p>{data.total} check-in(s) registrados. Este resumo não indica presença atual.</p>{data.arenas.map(a=><p key={a.id}>{a.name}</p>)}</div>:null}
export function CommonPlayers(){const{data,error}=useEntity<{id:string;username:string;display_name:string;arena_in_common:boolean;community_in_common:boolean;sport_in_common:boolean}[]>('/api/activity?kind=common');return <section className="arena-about"><h2>Pessoas com algo em comum</h2><p>Sugestões por vínculos e interesses visíveis. Seu histórico privado não participa desta busca.</p>{error&&<p role="alert">{error}</p>}{data?.map(p=><p key={p.id}><Link href={`/perfil/${p.username}`}>{p.display_name}</Link> · {[p.arena_in_common&&'arena',p.community_in_common&&'comunidade',p.sport_in_common&&'esporte'].filter(Boolean).join(', ')}</p>)}{data?.length===0&&<p>Acompanhe arenas e participe de comunidades para encontrar sua turma.</p>}</section>}

export function RecentArenas(){const{data}=useEntity<Checkin[]>('/api/activity?offset=0');const seen=new Set<string>();const recent=(data||[]).filter(c=>{if(seen.has(c.arena_id))return false;seen.add(c.arena_id);return true}).slice(0,4);return recent.length?<section className="arena-about"><h2>Arenas recentes</h2>{recent.map(c=><p key={c.arena_id}><Link href={`/checkin?arena=${c.arena_slug}`}>{c.arena_name} · novo check-in</Link></p>)}<p className="form-note">Locais do seu histórico; não indicam presença atual.</p></section>:null}
