// Real browser UI against the exclusive hosted-development backend.
import{chromium}from'../.vercel/browser-qa/node_modules/playwright/index.mjs';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import assert from'node:assert/strict';import sharp from'sharp';import{randomBytes}from'node:crypto';import{assertRemoteIdentity}from'../scripts/environment-guard.mjs';
await assertRemoteIdentity(process.env,'hosted-test');process.umask(0o077);const origin='http://localhost:3002',f=JSON.parse(readFileSync('.vercel/cycle9-fixture.json')),folder='.vercel/cycle9-ui';mkdirSync(folder,{recursive:true});const save=()=>writeFileSync('.vercel/cycle9-fixture.json',JSON.stringify(f,null,2));const browser=await chromium.launch();let checks=0;const errors=[];
async function account(label){const u=f.users.find(x=>x.label===label),context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',async r=>{if(r.request().method()==='POST'&&r.ok()){try{const b=r.request().postDataJSON(),d=await r.json();if(r.url().includes('/api/communities')&&b.action==='create'&&d.data?.id&&!f.communities.includes(d.data.id)){f.communities.push(d.data.id);save()}if(r.url().includes('/api/media?')&&d.data?.path&&!f.files.some(x=>x.path===d.data.path)){f.files.push({bucket:d.data.bucket,path:d.data.path});save()}}catch{}}});await page.goto(origin+'/login');await page.getByLabel('E-mail',{exact:true}).fill(u.email);await page.getByLabel('Senha',{exact:true}).fill(u.password);await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.waitForURL('**/perfil');await page.getByRole('heading',{level:1}).waitFor();checks++;return{u,context,page}}
async function shot(page,name){await page.screenshot({path:folder+'/'+name+'.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,'horizontal overflow '+name);checks++}
async function api(page,path,body){return page.evaluate(async({path,body})=>{const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});return{status:r.status,data:await r.json()}},{path,body})}
try{
 const owner=await account('owner-a'),member=await account('member'),moderator=await account('moderator'),root=await account('admin');const p=owner.page,m=member.page;console.log('Four accounts logged in through the UI');void moderator;
 // Controlled preparation only: undo the deliberately tested bilateral block.
 await api(m,'/api/social/mutate',{action:'set_block',playerId:owner.u.id,blocked:false});
 let groupUrl; if(f.uiGroup){groupUrl=origin+'/comunidades/'+f.uiGroup.slug;await p.goto(groupUrl);await p.getByRole('heading',{name:'Turma criada pela interface C9'}).waitFor();console.log('Resuming after verified community creation, approval and publication');}else{
 await p.goto(origin+'/comunidades');await p.getByRole('button',{name:'Criar comunidade',exact:true}).click();const dialog=p.getByRole('dialog');await dialog.getByLabel('Nome',{exact:true}).fill('Turma criada pela interface C9');await dialog.getByLabel('Quem vê o conteúdo').selectOption('private');await dialog.getByLabel('Como participar').selectOption('approval');await dialog.getByRole('button',{name:'Criar minha comunidade'}).click();await p.waitForURL('**/comunidades/grupo-*');groupUrl=p.url();await p.getByRole('heading',{name:'Turma criada pela interface C9'}).waitFor();checks++;
 await m.goto(groupUrl);await m.getByRole('button',{name:'Solicitar participação'}).click();await m.getByText('Pedido de entrada enviado.').waitFor();await p.getByRole('link',{name:'Gerenciar comunidade',exact:true}).click();await p.getByRole('button',{name:'Aprovar entrada'}).click();await p.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await m.reload();await m.getByText('Sobre a comunidade',{exact:true}).waitFor();checks++;
 await p.goto(groupUrl);await p.getByLabel('Sua publicação').fill('Publicação privada criada pela interface');await p.getByRole('button',{name:'Publicar no grupo privado'}).click();await p.getByText('Publicado nos destinos escolhidos.').waitFor();await m.reload();await m.getByText('Publicação privada criada pela interface',{exact:true}).waitFor();checks++;

 f.uiGroup={slug:new URL(groupUrl).pathname.split('/').at(-1)};save();}
 const groupPath=new URL(groupUrl).pathname;
 await p.goto(origin+'/perfil');await p.getByRole('heading',{level:1}).waitFor();await shot(p,'profile-390');
 // Generate a bounded >3MB camera-like original with EXIF orientation, no personal images copied.
 const input=folder+'/large-exif.jpg';await sharp(randomBytes(3000*2000*3),{raw:{width:3000,height:2000,channels:3}}).withMetadata({orientation:6}).jpeg({quality:96}).toFile(input);assert.ok(readFileSync(input).length>3*1024*1024);
 const before=await api(p,'/api/social/read?resource=profile');
 await p.getByText('Editar foto de perfil',{exact:true}).click();const file=p.locator('input[type=file]').first();await file.setInputFiles(input);await p.getByRole('dialog',{name:'Ajustar foto'}).waitFor();await p.getByRole('slider',{name:'Zoom da foto'}).fill('1.6');await p.getByRole('button',{name:'Girar 90°'}).click();await p.getByRole('slider',{name:'Zoom da foto'}).fill('1.3');await shot(p,'crop-390');await p.getByRole('button',{name:'Cancelar',exact:true}).click();assert.deepEqual((await api(p,'/api/social/read?resource=profile')).data,before.data);checks++;
 await file.setInputFiles(input);await p.getByRole('dialog',{name:'Ajustar foto'}).waitFor();await p.route('**/api/media?*',route=>route.request().method()==='POST'?route.abort('failed'):route.continue());await p.getByRole('button',{name:'Confirmar enquadramento'}).click();await p.getByRole('dialog').getByRole('alert').waitFor();assert.deepEqual((await api(p,'/api/social/read?resource=profile')).data,before.data);await p.unroute('**/api/media?*');await p.getByRole('button',{name:'Confirmar enquadramento'}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.getByRole('button',{name:'Usar esta foto',exact:true}).click();await p.getByText('Foto de perfil atualizada.').waitFor();await p.reload();checks++;console.log('Crop cancellation, interrupted upload and saved avatar passed');
 const profile=await api(p,'/api/social/read?resource=profile');writeFileSync(folder+'/profile-contract.json',JSON.stringify({status:profile.status,keys:Object.keys(profile.data)}));
 // Forms survive a real browser offline transition; no action auto-replays.
 await p.goto(origin+'/feed');await p.getByLabel('Sua publicação').fill('Rascunho offline que não deve ser publicado');await owner.context.setOffline(true);await p.getByText(/Sem conexão\. Seus rascunhos/).waitFor();await p.getByRole('button',{name:'Publicar no meu perfil',exact:true}).click();await p.getByText(/repetir mantém a mesma publicação/).waitFor();assert.equal(await p.getByLabel('Sua publicação').inputValue(),'Rascunho offline que não deve ser publicado');await owner.context.setOffline(false);assert.equal(await p.getByLabel('Sua publicação').inputValue(),'Rascunho offline que não deve ser publicado');checks++;
 for(const width of[320,390,430]){await p.setViewportSize({width,height:844});await shot(p,'feed-'+width);await p.goto(groupUrl);await shot(p,'community-'+width);await root.page.setViewportSize({width,height:844});await root.page.goto(origin+'/admin');await root.page.getByText('Suas arenas',{exact:true}).waitFor();await shot(root.page,'admin-'+width)}
 await p.goto(origin+'/instalar');await p.getByRole('heading',{name:'Instalar o Pico'}).waitFor();await shot(p,'install');
 const version=await p.request.get(origin+'/api/version');assert.ok((await version.json()).version);const manifest=await(await p.request.get(origin+'/manifest.webmanifest')).json();assert.equal(manifest.id,'/');assert.equal(manifest.scope,'/');assert.equal(manifest.display,'standalone');checks++;
 // Foreground refresh and a second tab sign-out must discard an existing draft.
 await p.goto(origin+'/feed');await p.getByLabel('Sua publicação').fill('Rascunho da conta anterior');const second=await owner.context.newPage();await second.goto(origin+'/login');await second.getByRole('button',{name:'Sair da conta',exact:true}).click();await p.waitForURL('**/login');assert.equal(await p.getByText('Rascunho da conta anterior').count(),0);checks++;
 { if(errors.length)throw Error('Browser runtime errors: '+errors.slice(0,3).join('; ')); }
 writeFileSync(folder+'/result.json',JSON.stringify({passed:true,checks,viewports:[320,390,430],browser:'Chromium 145 emulation',physicalDevices:false,realCameraPhoto:false,groupPath},null,2));console.log('Browser UI PASS',checks,'checks; mobile emulation, not physical devices');
}catch(e){for(const context of browser.contexts())for(const page of context.pages()){try{await page.screenshot({path:folder+'/failure-'+browser.contexts().indexOf(context)+'.png',fullPage:true})}catch{}}throw e}finally{await browser.close()}
