import assert from'node:assert/strict';import{randomBytes,randomUUID}from'node:crypto';import{spawnSync}from'node:child_process';import{readFileSync,writeFileSync}from'node:fs';import{createClient}from'@supabase/supabase-js';import{createServerClient}from'@supabase/ssr';import sharp from'sharp';import{assertRemoteIdentity}from'../scripts/environment-guard.mjs';
await assertRemoteIdentity(process.env,'hosted-test');process.umask(0o077);
const origin=process.env.PICO_TEST_ORIGIN||'http://localhost:3002',url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,secret=process.env.SUPABASE_SECRET_KEY,ref=process.env.PICO_PROJECT_REF;
assert.ok(['http://localhost:3002','http://localhost:3000'].includes(origin),'Full destructive suite runs only against the exclusive dev app');
const options={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:(i,o)=>fetch(i,{...o,signal:AbortSignal.timeout(25000)})}},admin=createClient(url,secret,options),anon=createClient(url,key,options),fixture={ref,users:[],arenas:[],communities:[],files:[],requests:[],emails:[]};let checks=0,success=false;
const check=(condition,label)=>{assert.ok(condition,label);checks++};
function ok(r,label){if(r.error)throw Error(label+': '+r.error.code);checks++;return r.data}
function denied(r,label){assert.ok(r.error,label+' should be denied');checks++}
function sql(q){const r=spawnSync('npx',['--yes','supabase@2.117.0','db','query','--linked',q],{encoding:'utf8',env:process.env,timeout:60000,maxBuffer:4e6});if(r.status!==0)throw Error('Controlled SQL preparation failed');return r.stdout}
function persist(){writeFileSync('.vercel/cycle9-fixture.json',JSON.stringify(fixture,null,2),{mode:0o600})}
function session(){const jar=new Map(),client=createServerClient(url,key,{cookies:{getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:entries=>entries.forEach(({name,value})=>value?jar.set(name,value):jar.delete(name))}});return{jar,client}}
async function user(label){const email=`pico-c9-${randomBytes(6).toString('hex')}-${label}@example.com`,password=randomBytes(24).toString('base64url')+'aA9!';fixture.emails.push(email);sql(`insert into pico_private.invitations(kind,email,token_hash,expires_at) values('beta','${email}','${randomBytes(32).toString('hex')}',now()+interval '1 hour')`);const current=session(),data=ok(await current.client.auth.signUp({email,password,options:{data:{display_name:'Teste C9 '+label}}}),'signup '+label);check(data.session&&data.user,'real signup session');const account={...current,id:data.user.id,email,password,label};fixture.users.push({id:account.id,email,password,label});persist();return account}
async function http(a,path,method='GET',body,status=200,type='application/json'){const r=await fetch(origin+path,{method,headers:{Origin:origin,Cookie:a?[...a.jar].map(([k,v])=>k+'='+v).join('; '):'',...(body?{'Content-Type':type}:{})},body:body===undefined?undefined:type==='application/json'?JSON.stringify(body):body,redirect:'manual',signal:AbortSignal.timeout(45000)});check(r.status===status,`${method} ${path.split('?')[0]} expected ${status}, received ${r.status}`);for(const h of r.headers.getSetCookie()){const part=h.split(';')[0],i=part.indexOf('=');if(a)a.jar.set(part.slice(0,i),part.slice(i+1))}check(/no-store/.test(r.headers.get('cache-control')||''),'private HTTP cache');return r}
async function api(a,path,body,status=200){const r=await http(a,path,body?'POST':'GET',body,status);const json=await r.json();return json.data??json}
const rpc=(a,name,args)=>a.client.rpc(name,args);
async function upload(a,bucket,scope){const bytes=await sharp({create:{width:180,height:120,channels:3,background:'#21bb98'}}).withMetadata({orientation:6}).jpeg().toBuffer();const params=new URLSearchParams({bucket,...scope}),r=await http(a,'/api/media?'+params,'POST',bytes,200,'image/jpeg'),data=(await r.json()).data;fixture.files.push({bucket,path:data.path});persist();return data.path}
async function group(a,name,visibility='beta',entry_mode='open'){const g=await api(a,'/api/communities',{action:'create',data:{name,visibility,entry_mode,description:'Grupo controlado para validação',rules:'Teste interno',sports:[]}});fixture.communities.push(g.id);persist();return g}
async function cleanup(){const saved=fixture.users.length?fixture:JSON.parse(readFileSync('.vercel/cycle9-fixture.json','utf8'));check(saved.ref===ref,'cleanup ref');for(const file of saved.files)ok(await admin.storage.from(file.bucket).remove([file.path]),'tracked file cleanup');const ids=saved.users.map(u=>u.id);if(ids.length){ok(await admin.from('posts').delete().in('author_id',ids),'tracked posts cleanup');ok(await admin.from('checkins').delete().in('player_id',ids),'tracked legacy cleanup');ok(await admin.from('played_games').delete().in('player_id',ids),'tracked games cleanup');if(saved.communities.length)sql(`delete from public.communities where id=any(array[${saved.communities.map(x=>"'"+x+"'::uuid").join(',')}])`);if(saved.arenas.length)sql(`delete from public.arenas where id=any(array[${saved.arenas.map(x=>"'"+x+"'::uuid").join(',')}])`);for(const u of saved.users){const result=await admin.auth.admin.deleteUser(u.id);if(result.error?.status!==404)ok(result,'tracked identity cleanup')}}for(const email of saved.emails)sql(`delete from pico_private.invitations where email='${email}'`);writeFileSync('.vercel/cycle9-fixture-cleaned.json',JSON.stringify({ref,users:ids.length,completed:true}),{mode:0o600});console.log('Tracked development fixtures cleaned')}
if(process.argv.includes('--cleanup')){await cleanup();process.exit(0)}
try{
 const blocked=await anon.auth.signUp({email:`pico-uninvited-${randomBytes(6).toString('hex')}@example.com`,password:randomBytes(24).toString('base64url')});denied(blocked,'uninvited direct signup');check(ok(await anon.from('arenas').select('id'),'anonymous gate').length===0,'anonymous no arena data');
 console.log('Admission and signup checks started');const root=await user('admin'),mod=await user('moderator'),owner=await user('owner-a'),other=await user('owner-b'),member=await user('member'),visitor=await user('visitor'),pending=await user('pending');const all=[root,mod,owner,other,member,visitor,pending];
 check(ok(await rpc(pending,'beta_status'),'pending').admitted===false,'new invited signup is not admitted');check(ok(await pending.client.from('profiles').select('id'),'pending profile').length===0,'pending profile gated');
 ok(await admin.rpc('bootstrap_operator',{p_uid:root.id}),'protected bootstrap');denied(await rpc(member,'bootstrap_operator',{p_uid:member.id}),'member bootstrap');
 for(const a of all.filter(a=>a!==root&&a!==pending)){ok(await rpc(root,'operator_action',{p_action:'beta_status',p_target_id:a.id,p_value:'approved'}),'approve test account');}
 ok(await rpc(root,'operator_action',{p_action:'platform_role',p_target_id:mod.id,p_value:'moderator'}),'assign moderator');
 for(const a of all.filter(a=>a!==pending)){const r=await a.client.from('profiles').update({display_name:'Teste C9 '+a.label,username:'c9_'+a.id.replaceAll('-','').slice(0,12),city:'Teste',neighborhood:'Teste',onboarding_completed:true}).eq('id',a.id).select('username').single();a.username=ok(r,'complete profile').username;fixture.users.find(u=>u.id===a.id).username=a.username}
 const sports=ok(await owner.client.from('sports').select('id').limit(1),'sports'),sport=sports[0].id;
 for(const a of[owner,other]){const id=randomUUID();fixture.arenas.push(id);persist();sql(`insert into public.arenas(id,slug,name,city,neighborhood,is_demo,owner_id) values('${id}','c9-${id.slice(0,8)}','Arena teste C9 ${a.label}','Teste','Teste',true,'${a.id}');insert into public.arena_sports(arena_id,sport_id) values('${id}','${sport}');insert into public.arena_members(arena_id,player_id) values('${id}','${a.id}')`);a.arena=id;a.slug='c9-'+id.slice(0,8)}
 console.log('Seven identities prepared; testing scopes');const arena=await api(owner,'/api/arenas?slug='+owner.slug);await api(owner,'/api/arenas',{action:'edit',id:owner.arena,version:arena.version,data:{name:'Arena C9 editada',city:'Teste',neighborhood:'Teste',description:'Edição confirmada',public_info:'',sports:[sport]}});check((await api(owner,'/api/arenas?slug='+owner.slug)).name==='Arena C9 editada','arena persisted');
 await api(member,'/api/arenas',{action:'edit',id:owner.arena,version:2,data:{name:'Ataque',sports:[]}},403);denied(await rpc(other,'save_arena',{p_id:owner.arena,p_version:2,p_data:{name:'Cruzado',sports:[]}}),'other arena owner');denied(await rpc(member,'operator_action',{p_action:'arena_role',p_scope_id:owner.arena,p_target_id:member.id,p_value:'admin'}),'self promotion');
 await api(member,'/api/arenas',{action:'follow',id:owner.arena,join:true});await api(owner,'/api/arenas',{action:'follow',id:other.arena,join:true});
 const pub=await group(owner,'Turma pública C9'),privateGroup=await group(owner,'Turma privada C9','private','approval'),independent=await group(other,'Turma independente C9');
 await api(member,'/api/communities',{action:'membership',id:pub.id,memberAction:'join'});await api(member,'/api/communities',{action:'membership',id:privateGroup.id,memberAction:'join'});check((await api(member,'/api/communities?kind=page&slug='+privateGroup.slug)).readable===false,'pending private group hidden');await api(owner,'/api/communities',{action:'membership',id:privateGroup.id,memberAction:'approve',target:member.id});await api(owner,'/api/communities',{action:'membership',id:privateGroup.id,memberAction:'role',target:member.id,role:'moderator'});
 denied(await rpc(member,'community_membership',{p_id:privateGroup.id,p_action:'role',p_target:member.id,p_role:'admin'}),'community moderator escalation');denied(await rpc(owner,'save_community',{p_id:independent.id,p_version:1,p_data:{name:'Cross',sports:[],visibility:'beta',entry_mode:'open'}}),'cross group owner');
 await api(other,'/api/communities',{action:'link',id:independent.id,arena:owner.arena,linkAction:'request'});denied(await rpc(other,'community_link',{p_community:independent.id,p_arena:owner.arena,p_action:'approve'}),'self official linking');await api(owner,'/api/communities',{action:'link',id:independent.id,arena:owner.arena,linkAction:'approve',official:true});
 const invite=await api(owner,'/api/arenas',{action:'invite',id:owner.arena,email:visitor.email,role:'admin'});denied(await rpc(other,'accept_arena_invite',{p_token:invite.token}),'copied invitation');const concurrent=await Promise.all([rpc(visitor,'accept_arena_invite',{p_token:invite.token}),rpc(visitor,'accept_arena_invite',{p_token:invite.token})]);check(concurrent.filter(r=>!r.error).length===1,'one concurrent invite acceptance');check((await api(visitor,'/api/arenas?slug='+owner.slug)).rank===30,'invited manager rank');
 const avatar=await upload(owner,'avatars'),photo=await upload(member,'post-media'),cover=await upload(owner,'entity-media',{kind:'community',id:privateGroup.id,slot:'cover'});await api(owner,'/api/social/mutate',{action:'set_avatar',path:avatar});await api(owner,'/api/entity-photos',{kind:'community',id:privateGroup.id,slot:'cover',path:cover});await http(other,'/api/media?bucket=entity-media&path='+encodeURIComponent(cover),'GET',undefined,404);
 const bytes=await http(member,'/api/media?bucket=entity-media&path='+encodeURIComponent(cover));check((await sharp(Buffer.from(await bytes.arrayBuffer())).metadata()).exif===undefined,'normalized metadata-free bytes');
 denied(await owner.client.storage.from('avatars').createSignedUrl(avatar,60),'private signing blocked');denied(await owner.client.storage.from('avatars').download(avatar),'direct Storage blocked');await http(visitor,'/api/media?bucket=avatars','POST',Buffer.alloc(3*1024*1024+1),413,'image/png');await http(member,'/api/media?bucket=avatars','POST',Buffer.from('invalid'),400,'image/png');
 console.log('Photo and invitation checks passed; testing publications');const pkey=randomUUID(),args={p_key:pkey,p_body:'Um único post em vários destinos',p_audience:'beta',p_wall_arena:owner.arena,p_groups:[pub.id]};const concurrentPosts=await Promise.all([rpc(owner,'publish_post',args),rpc(owner,'publish_post',args)]),post=ok(concurrentPosts[0],'publish 1');check(ok(concurrentPosts[1],'publish duplicate')===post,'canonical idempotent result');check(ok(await rpc(owner,'read_social_feed'),'feed').filter(p=>p.id===post).length===1,'feed deduplication');check(ok(await rpc(owner,'read_social_feed',{p_arena:owner.arena}),'wall').some(p=>p.id===post),'arena destination');check(ok(await rpc(owner,'read_social_feed',{p_community:pub.id}),'group feed').some(p=>p.id===post),'group destination');
 const privatePost=ok(await rpc(member,'publish_post',{p_key:randomUUID(),p_body:'Post privado C9',p_image_path:photo,p_audience:'private',p_groups:[privateGroup.id]}),'private post');check(ok(await rpc(other,'read_social_feed',{p_author:member.id}),'private author feed').length===0,'private post hidden in profile');check(ok(await other.client.from('posts').select('id').eq('id',privatePost),'direct private post').length===0,'private ID hidden');denied(await other.client.from('comments').insert({post_id:privatePost,body:'Unauthorized'}),'private comment denied');
 ok(await member.client.from('post_likes').insert({post_id:post}),'like');ok(await member.client.from('comments').insert({post_id:post,body:'Comentário C9'}),'comment');check(ok(await rpc(owner,'read_social_feed',{p_post:post}),'engagement')[0].like_count===1,'canonical like count');
 ok(await rpc(owner,'remove_distribution',{p_post:post,p_community:pub.id}),'remove one distribution');check(ok(await rpc(owner,'read_social_feed',{p_arena:owner.arena}),'remaining destination').some(p=>p.id===post),'other destination preserved');
 await api(owner,'/api/communities',{action:'membership',id:privateGroup.id,memberAction:'suspend',target:member.id});await http(member,'/api/media?bucket=post-media&path='+encodeURIComponent(photo),'GET',undefined,404);await http(member,'/api/media?bucket=entity-media&path='+encodeURIComponent(cover),'GET',undefined,404);check(ok(await rpc(member,'read_social_feed',{p_post:privatePost}),'revoked own post').length===0,'private author loses access');
 const gameId=randomUUID(),gameInput={action:'save',id:gameId,arenaId:owner.arena,sportId:sport,playedOn:'2026-01-02'};
 const concurrentGames=await Promise.all([api(owner,'/api/games',gameInput),api(owner,'/api/games',gameInput)]);
 check(concurrentGames.every(game=>game.id===gameId),'concurrent game requests return one identity');
 check((await api(owner,'/api/games')).filter(g=>g.id===gameId).length===1,'idempotent own game');
 check((await api(other,'/api/games')).length===0,'other private journal');
 check(ok(await other.client.from('played_games').select('id').eq('id',gameId),'direct game RLS').length===0,'foreign game hidden');
 await api(other,'/api/games',{...gameInput,version:1,playedOn:'2026-01-03'},403);
 await api(other,'/api/games',{action:'delete',id:gameId});
 const untouchedGame=(await api(owner,'/api/games')).find(g=>g.id===gameId);
 check(untouchedGame?.version===1&&untouchedGame.played_on==='2026-01-02','foreign delete is an idempotent no-op; owner data unchanged');
 await api(owner,'/api/games',{...gameInput,playedOn:'2999-01-01'},400);
 const gameShare={id:gameId,version:1,key:randomUUID(),body:'Relato privado do jogo',audience:'private',groups:[privateGroup.id]};
 const concurrentShares=await Promise.all([api(owner,'/api/games/share',gameShare),api(owner,'/api/games/share',gameShare)]),shared=concurrentShares[0];
 check(concurrentShares[1]===shared,'concurrent shared game requests return one canonical post');
 check(await api(owner,'/api/games/share',gameShare)===shared,'idempotent shared game post');
 check(ok(await rpc(owner,'read_social_feed',{p_post:shared}),'own shared game')[0].game_played_on==='2026-01-02','game date snapshot');
 check(ok(await rpc(other,'read_social_feed',{p_post:shared}),'private shared game').length===0,'private shared game denied');
 await api(owner,'/api/games',{...gameInput,version:1,playedOn:'2026-01-03'});
 await api(owner,'/api/games',{action:'delete',id:gameId});
 check(ok(await rpc(owner,'read_social_feed',{p_post:shared}),'snapshot after game deletion')[0].game_played_on==='2026-01-02','shared snapshot survives private correction/deletion');
 await api(owner,'/api/games',gameInput,409);
 denied(await rpc(owner,'start_checkin',{arena_id:owner.arena,sport_id:sport}),'retired creation');denied(await rpc(owner,'end_checkin'),'retired ending');denied(await rpc(other,'activity_summary',{p_player:owner.id}),'retired summary');
 check((await api(owner,'/api/games/legacy')).length===0,'new account has no legacy conversion');
 const report=ok(await member.client.from('reports').insert({post_id:post,reason:'spam'}).select('id').single(),'report').id;ok(await member.client.from('blocks').insert({blocked_id:owner.id}),'block');check(ok(await rpc(member,'read_social_feed',{p_post:post}),'blocked feed').length===0,'block effect');await api(mod,'/api/manage',{action:'moderate_report',target:report,value:'hide'});check(ok(await admin.from('posts').select('moderated_at').eq('id',post).single(),'moderation persisted').moderated_at,'real moderation effect');
 ok(await rpc(root,'operator_action',{p_action:'beta_status',p_target_id:other.id,p_value:'suspended'}),'suspend admission');check(ok(await other.client.from('arenas').select('id'),'old jwt query').length===0,'old JWT no data after suspension');ok(await rpc(root,'operator_action',{p_action:'beta_status',p_target_id:other.id,p_value:'approved'}),'restore admission');
 const login=session();ok(await login.client.auth.signInWithPassword({email:owner.email,password:owner.password}),'real login');const refreshed=ok(await login.client.auth.refreshSession(),'real refresh');check(refreshed.user.id===owner.id,'refresh identity');check((await api(login,'/api/access')).admitted===true,'SSR cookie persisted session');
 const recovery=ok(await admin.auth.admin.generateLink({type:'recovery',email:visitor.email}),'controlled recovery link');const fresh=session();const response=await http(fresh,'/api/auth/confirm','POST',{type:'recovery',token_hash:recovery.properties.hashed_token});check((await response.json()).next==='/redefinir-senha','cross context recovery endpoint');const recovered=session();for(const[k,v]of fresh.jar)recovered.jar.set(k,v);check(ok(await recovered.client.auth.getUser(),'recovered user').user.id===visitor.id,'token established isolated browser session');const newPassword=randomBytes(24).toString('base64url')+'aA9!';ok(await recovered.client.auth.updateUser({password:newPassword}),'new password');visitor.password=newPassword;fixture.users.find(u=>u.id===visitor.id).password=newPassword;ok(await session().client.auth.signInWithPassword({email:visitor.email,password:newPassword}),'new password login');await http(session(),'/api/auth/confirm','POST',{type:'recovery',token_hash:recovery.properties.hashed_token},400);
 denied(await rpc(root,'operator_action',{p_action:'beta_status',p_target_id:root.id,p_value:'revoked'}),'last admin');
 for(const a of all){fixture.users.find(u=>u.id===a.id).cookies=[...a.jar].map(([name,value])=>({name,value}))}fixture.sport=sport;fixture.publicGroup=pub;fixture.privateGroup=privateGroup;persist();success=true;
 writeFileSync('.vercel/cycle9-hosted-result.json',JSON.stringify({ref,origin,checks,passed:true,roles:all.map(a=>a.label),emailDeliveryVerified:false},null,2));console.log('Hosted cycle 9 PASS',checks,'checks; real Auth/Data API/Storage/HTTP; no inbox delivery claimed');
}finally{if(!success||!process.argv.includes('--keep'))await cleanup();else console.log('Controlled fixtures retained privately for UI and restoration rehearsal');}
