export const ORIGINAL_LIMIT=20*1024*1024,PIXEL_LIMIT=25_000_000,UPLOAD_LIMIT=3*1024*1024;
export type CropArea={x:number;y:number;width:number;height:number};
export function inspectImage(bytes:Uint8Array):{width:number;height:number;format:'jpeg'|'png'|'webp'}{
 const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),text=(o:number,n:number)=>String.fromCharCode(...bytes.subarray(o,o+n));let width=0,height=0,format:'jpeg'|'png'|'webp';
 if(bytes.length>=24&&v.getUint32(0)===0x89504e47&&v.getUint32(4)===0x0d0a1a0a){format='png';width=v.getUint32(16);height=v.getUint32(20);for(let p=8;p+12<=bytes.length;){const size=v.getUint32(p);if(text(p+4,4)==='acTL')throw Error('Use uma foto estática, sem animação.');if(size>bytes.length-p-12)break;p+=size+12;}}
 else if(bytes.length>=30&&text(0,4)==='RIFF'&&text(8,4)==='WEBP'){format='webp';const kind=text(12,4);if(kind==='VP8X'){if(bytes[20]&2)throw Error('Use uma foto estática, sem animação.');width=1+bytes[24]+(bytes[25]<<8)+(bytes[26]<<16);height=1+bytes[27]+(bytes[28]<<8)+(bytes[29]<<16);}else if(kind==='VP8 '){if(text(23,3)!=='\x9d\x01\x2a')throw Error('Foto WebP inválida.');width=v.getUint16(26,true)&0x3fff;height=v.getUint16(28,true)&0x3fff;}else if(kind==='VP8L'&&bytes[20]===0x2f){const bits=v.getUint32(21,true);width=1+(bits&0x3fff);height=1+((bits>>>14)&0x3fff);}}
 else if(bytes.length>4&&bytes[0]===255&&bytes[1]===216){format='jpeg';let p=2;while(p+4<=bytes.length){if(bytes[p]!==255)break;while(bytes[p]===255)p++;const marker=bytes[p++];if(marker===0xda||marker===0xd9)break;if(marker===0x01||(marker>=0xd0&&marker<=0xd7))continue;const size=v.getUint16(p);if(size<2||p+size>bytes.length)break;if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)&&size>=7){height=v.getUint16(p+3);width=v.getUint16(p+5);break;}p+=size;}}
 else throw Error('Formato não suportado. Exporte a foto como JPEG, PNG ou WebP. HEIC/HEIF ainda não é suportado.');
 if(!width||!height||width>16000||height>16000||width*height>PIXEL_LIMIT)throw Error('Use uma foto com até 25 megapixels e 16.000 pixels por lado.');
 return{width,height,format};
}
export function rotationBounds(width:number,height:number,rotation:number){const radians=rotation*Math.PI/180;return{width:Math.ceil(Math.abs(Math.cos(radians))*width+Math.abs(Math.sin(radians))*height-1e-8),height:Math.ceil(Math.abs(Math.sin(radians))*width+Math.abs(Math.cos(radians))*height-1e-8)}}
function blob(canvas:HTMLCanvasElement,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(Error('Não foi possível processar a foto.')),'image/webp',quality))}
export async function preparePhoto(file:File){if(file.size>ORIGINAL_LIMIT)throw Error('O original deve ter até 20 MB. Exporte uma versão menor.');if(/\.hei[cf]$/i.test(file.name)||/image\/hei[cf]/i.test(file.type))throw Error('HEIC/HEIF ainda não é suportado. Exporte como JPEG no app Fotos e tente novamente.');inspectImage(new Uint8Array(await file.arrayBuffer()));
 if(typeof createImageBitmap!=='function')throw Error('Este navegador não oferece o processamento necessário. Abra no Safari ou Chrome atualizado.');
 const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});try{if(bitmap.width*bitmap.height>PIXEL_LIMIT)throw Error('Foto acima do limite de pixels.');const scale=Math.min(1,2048/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');if(!context)throw Error('Editor indisponível.');context.drawImage(bitmap,0,0,canvas.width,canvas.height);const result=await blob(canvas,.94);const info={url:URL.createObjectURL(result),width:canvas.width,height:canvas.height};canvas.width=canvas.height=1;return info;}finally{bitmap.close();}}
export async function renderCrop(url:string,area:CropArea,rotation:number,maxSide:number){const response=await fetch(url);const bitmap=await createImageBitmap(await response.blob());try{const bounds=rotationBounds(bitmap.width,bitmap.height,rotation),canvas=document.createElement('canvas');canvas.width=bounds.width;canvas.height=bounds.height;const c=canvas.getContext('2d');if(!c)throw Error('Editor indisponível.');c.translate(bounds.width/2,bounds.height/2);c.rotate(rotation*Math.PI/180);c.drawImage(bitmap,-bitmap.width/2,-bitmap.height/2);const output=document.createElement('canvas'),scale=Math.min(1,maxSide/Math.max(area.width,area.height));output.width=Math.max(1,Math.round(area.width*scale));output.height=Math.max(1,Math.round(area.height*scale));const target=output.getContext('2d');if(!target)throw Error('Editor indisponível.');target.drawImage(canvas,area.x,area.y,area.width,area.height,0,0,output.width,output.height);canvas.width=canvas.height=1;let result=await blob(output,.88);if(result.size>UPLOAD_LIMIT)result=await blob(output,.7);output.width=output.height=1;if(result.size>UPLOAD_LIMIT)throw Error('O recorte ainda está grande. Escolha uma área menor.');return result;}finally{bitmap.close();}}
