// Generated by node scripts/generate-pending-functions.mjs from local migrations.
// Pending hosted regeneration; do not edit by hand.
import type { Json } from './database';

export type PendingFunctions = {
  claim_push_batch: { Args: { p_limit?: number }; Returns: { job_id: string; lease_token: string }[] };
  delete_push_subscription: { Args: { p_endpoint: string }; Returns: undefined };
  export_account_messages: { Args: { p_user: string }; Returns: Json };
  finish_push_delivery: { Args: { p_job: string; p_lease: string; p_outcome: string; p_retry_after?: number }; Returns: undefined };
  mark_direct_messages_read: { Args: { p_conversation: string; p_through: string }; Returns: undefined };
  open_direct_conversation: { Args: { p_player: string }; Returns: Json };
  read_direct_conversations: { Args: { p_before?: string }; Returns: Json };
  read_direct_messages: { Args: { p_conversation: string; p_before?: string }; Returns: Json };
  read_push_delivery: { Args: { p_job: string; p_lease: string }; Returns: Json };
  read_push_subscription: { Args: { p_endpoint?: string }; Returns: Json };
  save_push_subscription: { Args: { p_endpoint: string; p_p256dh: string; p_auth: string }; Returns: undefined };
  send_direct_message: { Args: { p_conversation: string; p_key: string; p_body: string }; Returns: Json };
};
