// Run with a protected env file. Read-only remote export; never resets a database.
import{mkdirSync,readFileSync,writeFileSync,chmodSync,readdirSync,copyFileSync,rmSync}from'node:fs';import{resolve,join}from'node:path';import{spawnSync}from'node:child_process';import{randomBytes,createCipheriv,createHash}from'node:crypto';import{createClient}from'@supabase/supabase-js';import{assertRemoteIdentity}from'./environment-guard.mjs';
process.umask(0o077);const env=await assertRemoteIdentity(process.env,'backup');
const id=new Date().toISOString().replace(/[:.]/g,'-'),root=resolve('.vercel/backups/'+env.purpose+'-'+id),raw=join(root,'raw');mkdirSync(raw,{recursive:true,mode:0o700});
function run(args){const r=spawnSync('npx',['--yes','supabase@2.117.0',...args],{encoding:'utf8',env:process.env,timeout:300000,maxBuffer:8e6});if(r.status!==0)throw Error('Backup CLI failed; partial private export retained at '+root);return r.stdout;}
const wd=join(root,'work');mkdirSync(wd+'/supabase',{recursive:true});writeFileSync(wd+'/supabase/config.toml','project_id = "pico-backup"\n');run(['link','--project-ref',env.projectRef,'--workdir',wd]);
for(const[name,args]of[['roles.sql',['--role-only']],['schema.sql',['--schema','public,pico_private']],['auth-storage-schema.sql',['--schema','auth,storage']],['data.sql',['--data-only','--use-copy','--schema','public,pico_private,auth,storage','-x','auth.schema_migrations','-x','storage.migrations','-x','storage.objects','-x','storage.buckets','-x','storage.buckets_vectors','-x','storage.vector_indexes']],['migration-history.sql',['--data-only','--use-copy','--schema','supabase_migrations']]]){run(['db','dump','--linked','--workdir',wd,'--file',join(raw,name),...args]);chmodSync(join(raw,name),0o600)}
mkdirSync(raw+'/configuration/supabase',{recursive:true});writeFileSync(raw+'/configuration/supabase/config.toml','project_id = "pico-backup-config"\n');run(['config','pull','--project-ref',env.projectRef,'--workdir',raw+'/configuration']);
mkdirSync(raw+'/migrations');for(const file of readdirSync('supabase/migrations'))copyFileSync('supabase/migrations/'+file,raw+'/migrations/'+file);
const admin=createClient(env.url,process.env.SUPABASE_SECRET_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),buckets=await admin.storage.listBuckets();if(buckets.error)throw Error('Bucket inventory failed');writeFileSync(raw+'/buckets.json',JSON.stringify(buckets.data));const objects=[];
for(const bucket of buckets.data){const queue=[''];while(queue.length){const prefix=queue.shift();for(let offset=0;;offset+=100){const list=await admin.storage.from(bucket.id).list(prefix,{limit:100,offset});if(list.error)throw Error('Storage inventory failed');for(const item of list.data){const path=prefix?prefix+'/'+item.name:item.name;if(!item.id){queue.push(path);continue}if(!/^[a-zA-Z0-9_./-]+$/.test(path)||path.split('/').includes('..'))throw Error('Unsupported object name');const r=await admin.storage.from(bucket.id).download(path,{cacheNonce:id});if(r.error)throw Error('Storage download failed');const bytes=Buffer.from(await r.data.arrayBuffer()),file='storage/'+bucket.id+'/'+path;mkdirSync(resolve(raw,file,'..'),{recursive:true});writeFileSync(raw+'/'+file,bytes);objects.push({bucket:bucket.id,path,file,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length})}if(list.data.length<100)break}}}
writeFileSync(raw+'/manifest.json',JSON.stringify({format:1,createdAt:id,purpose:env.purpose,projectRef:env.projectRef,objects,notes:'Logical export; Auth sessions/encryption/provider versions require restore validation. Storage bytes are separate from SQL. No vault keys or SMTP secrets inferred.'},null,2));
const tar=spawnSync('tar',['-czf',root+'/payload.tgz','-C',raw,'.'],{timeout:120000});if(tar.status!==0)throw Error('Archive failed');const key=randomBytes(32),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([cipher.update(readFileSync(root+'/payload.tgz')),cipher.final()]);writeFileSync(root+'/backup.pico',Buffer.concat([Buffer.from('PICO1'),iv,cipher.getAuthTag(),encrypted]));writeFileSync(root+'/backup.key',key.toString('base64'));writeFileSync(root+'/receipt.json',JSON.stringify({projectRef:env.projectRef,createdAt:id,objects:objects.length,sha256:createHash('sha256').update(readFileSync(root+'/backup.pico')).digest('hex')},null,2));rmSync(raw,{recursive:true});rmSync(root+'/payload.tgz');rmSync(wd,{recursive:true});console.log('Encrypted backup created:',root,'objects:',objects.length,'Keep backup.key separately before any off-device copy.');
