import Link from 'next/link';
import { Brand } from '@/components/pico/Brand';
export const metadata={title:'Privacidade'};
export default function PrivacyPage(){
  return <div className="landing-shell"><header className="site-header"><Brand /><Link href="/feed">Voltar ao Pico</Link></header><main id="main-content" className="privacy-page"><h1>Privacidade no Pico.</h1><p>Atualizado em 13 de setembro de 2026. O Pico é uma rede social de esportes de areia, com cadastro aberto e confirmação de e-mail.</p>
    <h2>O que fica na sua conta</h2><p>Seu e-mail identifica a conta. A senha é verificada pelo serviço de autenticação, que guarda um hash, e não a senha em texto legível. Nome, username, bio, cidade, bairro, e esportes compõem seu perfil. Fotos, publicações, curtidas, comentários e conexões ficam salvos quando você usa essas ações.</p>
    <h2>Para que usamos os dados</h2><p>Para criar e proteger sua conta, mostrar o perfil e o conteúdo à audiência escolhida, conectar pessoas por esportes e comunidades, guardar seus jogos e atender pedidos de suporte e moderação. O Pico não usa publicidade direcionada.</p><h2>Sua primeira comunidade</h2><p>Ao concluir seu perfil e escolher uma modalidade, você entra automaticamente na comunidade oficial do Pico. Seu nome e perfil aparecem na lista de participantes. A confirmação dessa entrada é mostrada no aplicativo. Você pode sair nas opções de participação e não será adicionado novamente ao entrar ou editar o perfil.</p>
    <h2>Quem pode ver</h2><p>Pessoas cadastradas, com e-mail confirmado e conta ativa, podem ver seu perfil e conteúdo destinado ao Pico. Publicações de comunidades privadas, inclusive no perfil do autor e em links diretos, ficam restritas aos participantes ativos. Entrada por aprovação ou convite é diferente da audiência do grupo. Republicar mantém o autor e a audiência original: seguidores só recebem conteúdo que também têm permissão para ver. Você pode desfazer a republicação. Seu e-mail não aparece no perfil. A lista de pessoas que você acompanha, seus bloqueios, denúncias e fotos ainda não publicadas ficam privados para você e para a operação do serviço. Pessoas bloqueadas deixam de ver seu perfil, conteúdo e fotos; o efeito é recíproco.</p>
    <h2>Seus jogos e fotos</h2><p>Depois de jogar, você pode guardar arena, modalidade e data em Meus jogos. Esses registros são privados e podem ser corrigidos ou excluídos por você. A data do jogo é a data da experiência, não a de uma publicação. Registrar não publica no feed, em arenas ou comunidades e não avisa outras pessoas. Se você escolher Compartilhar jogo, uma publicação separada mostrará a data do jogo, a arena e o conteúdo que enviar à audiência e aos destinos escolhidos. Corrigir ou excluir o registro privado não altera essa publicação; ela deve ser editada ou excluída separadamente. O registro é autodeclarado e não comprova presença física. Não mostramos presença ao vivo nem coletamos localização contínua. Dados do recurso antigo são preservados sem exposição social e não viram novos registros. As fotos enviadas pelo aplicativo são reduzidas e convertidas, sem os metadados do arquivo original. Não publique informações sensíveis de outras pessoas. Quem consegue ver uma foto pode copiá-la; o bloqueio não apaga cópias feitas anteriormente.</p>
    <h2>Gestão e moderação</h2><p>Funções de gestão valem para a arena ou comunidade atribuída. A equipe do Pico controla admissão e moderação. Operadores podem examinar o conteúdo específico de uma denúncia e aplicar medidas, com registro de acesso; isso não libera leitura geral de grupos privados. Convites individuais exigem o e-mail destinatário e expiram.</p><h2>Armazenamento e sessão</h2><p>Supabase armazena as contas, dados e fotos; o banco principal está em São Paulo. Vercel hospeda o aplicativo. Serviços de infraestrutura, suporte e entrega podem envolver processamento fora do Brasil. Esses fornecedores também processam informações técnicas de acesso e segurança. Cookies mantêm sua sessão. Preferências de instalação e tutorial ficam neste navegador; o progresso do tutorial é separado por conta e demonstração. O Pico não usa anúncios, rastreamento publicitário nem cache offline de conteúdo privado. Depois de sair, entrar novamente é necessário para ler seus dados.</p>
    <h2>Seu controle</h2><p>Você pode editar seu perfil, remover a foto, excluir suas publicações e comentários, desfazer conexões e corrigir ou excluir seus registros de jogos. Em <Link href="/conta">Privacidade e conta</Link>, é possível baixar uma cópia dos dados da conta em JSON, desbloquear pessoas, acompanhar denúncias, remover fotos sem uso e excluir a conta com confirmação de senha. O download inclui referências das fotos, sem os arquivos de imagem. Em caso de suspensão, download e exclusão também ficam disponíveis em Acesso ao Pico.</p>
    <h2>Seus direitos</h2><p>Você pode pedir confirmação do tratamento, acesso, correção, informações sobre compartilhamento e avaliação de exclusão, anonimização, oposição ou revogação de consentimento, quando aplicáveis. A operação pode confirmar sua identidade para proteger o pedido. Não envie senhas. Correção, download e exclusão já podem ser iniciados no aplicativo.</p><h2>Exclusão e limites</h2><p>A exclusão remove a identidade, fotos pessoais, histórico e dados sociais vinculados da base ativa. Arenas e comunidades permanecem com responsabilidade transferida, custódia ou arquivamento. Fotos oficiais desses recursos podem permanecer; o vínculo pessoal de quem as enviou é removido. Registros técnicos mantidos pelos fornecedores seguem a retenção deles; o app não promete apagar imediatamente registros fora da base ativa ou cópias feitas por outras pessoas. Denúncias são analisadas pela operação, sem remoção automática por quantidade. Dados necessários ao funcionamento ficam enquanto a conta estiver ativa ou até sua remoção pelo titular, conforme o recurso. Cópias de segurança e registros técnicos têm ciclos separados; retenções legais precisam ser avaliadas pela operação. A definição do responsável, do canal de privacidade e dos prazos operacionais ainda está pendente para a abertura do beta.</p>
    {process.env.NEXT_PUBLIC_PRIVACY_CONTROLLER && <p>Responsável pelo tratamento: {process.env.NEXT_PUBLIC_PRIVACY_CONTROLLER}.</p>}{process.env.NEXT_PUBLIC_PRIVACY_CONTACT ? <p>Contato de privacidade: {process.env.NEXT_PUBLIC_PRIVACY_CONTACT}</p> : <p>O canal de contato de privacidade ainda não foi configurado. As ações da conta continuam disponíveis no aplicativo.</p>}<p><Link href="/conta">Gerenciar minha conta</Link> · <Link href="/recuperar">Recuperar acesso</Link></p>
  </main></div>;
}
