import Link from 'next/link';
import { Brand } from '@/components/pico/Brand';
export const metadata={title:'Privacidade'};
export default function PrivacyPage(){
  return <div className="landing-shell"><header className="site-header"><Brand /><Link href="/feed">Voltar ao Pico</Link></header><main id="main-content" className="privacy-page"><h1>Privacidade no Pico.</h1><p>Atualizado em 13 de setembro de 2026. O Pico é uma rede social de esportes de areia, com cadastro aberto e confirmação de e-mail.</p>
    <h2>O que fica na sua conta</h2><p>Usamos seu e-mail e senha para autenticar você. Nome, username, bio, cidade, bairro, esportes e disponibilidade compõem seu perfil. Fotos, publicações, curtidas, comentários e conexões ficam salvos quando você usa essas ações.</p>
    <h2>Sua primeira comunidade</h2><p>Ao concluir seu perfil e escolher uma modalidade, você entra automaticamente na comunidade oficial do Pico. Seu nome e perfil aparecem na lista de participantes. A confirmação dessa entrada é mostrada no aplicativo. Você pode sair nas opções de participação e não será adicionado novamente ao entrar ou editar o perfil.</p>
    <h2>Quem pode ver</h2><p>Pessoas cadastradas, com e-mail confirmado e conta ativa, podem ver seu perfil e conteúdo destinado ao Pico. Publicações de comunidades privadas, inclusive no perfil do autor e em links diretos, ficam restritas aos participantes ativos. Entrada por aprovação ou convite é diferente da audiência do grupo. Seu e-mail não aparece no perfil. A lista de pessoas que você acompanha, seus bloqueios, denúncias e fotos ainda não publicadas ficam privados para você e para a operação do serviço. Pessoas bloqueadas deixam de ver seu perfil, conteúdo e fotos; o efeito é recíproco.</p>
    <h2>Seus jogos e fotos</h2><p>Depois de jogar, você pode guardar arena, modalidade e data em Meus jogos. Esses registros são privados e podem ser corrigidos ou excluídos por você. A data do jogo é a data da experiência, não a de uma publicação. Registrar não publica no feed, em arenas ou comunidades e não avisa outras pessoas. Se você escolher Compartilhar jogo, uma publicação separada mostrará a data do jogo, a arena e o conteúdo que enviar à audiência e aos destinos escolhidos. Corrigir ou excluir o registro privado não altera essa publicação; ela deve ser editada ou excluída separadamente. O registro é autodeclarado e não comprova presença física. Não mostramos presença ao vivo nem coletamos localização contínua. Dados do recurso antigo são preservados sem exposição social e não viram novos registros. As fotos enviadas pelo aplicativo são reduzidas e convertidas, sem os metadados do arquivo original. Não publique informações sensíveis de outras pessoas. Quem consegue ver uma foto pode copiá-la; o bloqueio não apaga cópias feitas anteriormente.</p>
    <h2>Gestão e moderação</h2><p>Funções de gestão valem para a arena ou comunidade atribuída. A equipe do Pico controla admissão e moderação. Operadores podem examinar o conteúdo específico de uma denúncia e aplicar medidas, com registro de acesso; isso não libera leitura geral de grupos privados. Convites individuais exigem o e-mail destinatário e expiram.</p><h2>Armazenamento e sessão</h2><p>Supabase armazena as contas, dados e fotos; o banco está em São Paulo. Vercel hospeda o aplicativo. Esses fornecedores também processam informações técnicas de acesso e segurança. Cookies mantêm sua sessão. O Pico não usa anúncios, rastreamento publicitário nem cache offline de conteúdo privado. Depois de sair, entrar novamente é necessário para ler seus dados.</p>
    <h2>Seu controle</h2><p>Você pode editar seu perfil, remover a foto, excluir suas publicações e comentários, desfazer conexões e corrigir ou excluir seus registros de jogos. Em <Link href="/conta">Privacidade e conta</Link>, é possível desbloquear pessoas, acompanhar denúncias, remover fotos sem uso e excluir a conta com confirmação de senha.</p>
    <h2>Exclusão e limites</h2><p>A exclusão remove a identidade, fotos pessoais, histórico e dados sociais vinculados da base ativa. Arenas e comunidades permanecem com responsabilidade transferida, custódia ou arquivamento. Fotos oficiais desses recursos podem permanecer; o vínculo pessoal de quem as enviou é removido. Registros técnicos mantidos pelos fornecedores seguem a retenção deles; o app não promete apagar imediatamente registros fora da base ativa ou cópias feitas por outras pessoas. Denúncias são analisadas pela operação, sem remoção automática por quantidade. Antes da abertura ao público, faltam aprovar o canal de contato, responsáveis e a rotina de retenção e backup externo.</p>
    {process.env.NEXT_PUBLIC_PRIVACY_CONTACT&&<p>Contato informado pela operação: {process.env.NEXT_PUBLIC_PRIVACY_CONTACT}</p>}<p><Link href="/conta">Gerenciar minha conta</Link> · <Link href="/recuperar">Recuperar acesso</Link></p>
  </main></div>;
}
